### PR TITLE
Inline classes for URIs

### PR DESCRIPTION
**Pull request by molikuner**
* Implemented #14
* Using the inline classes internally

### CODE REVIEW

**Comment by adamint** [comment]
Many of the functions you changed have been changed as well as I clean up the code (unfortunately).

**Comment by adamint** [comment]
Alright, cool! I'll do a final review in a few hours

**Comment by adamint** [comment]
I didn't realize inline classes were still an experimental feature.. hmm. Since we're just using them internally, I think we can just make them regular classes for now.

The Spotify URI classes seemed a little verbose - extending from a base `SpotifyURI` abstract class seems a little cleaner - do you agree? 

It seems self-defeating to have backing properties against `uri` and `id` -  if the given input is invalid, we might as well complain when the class is instantiated

I think it would be better to throw a subtype of `BadRequestionException` in the `SpotifyUri` classes instead of `IllegalArgumentException` to make it a little more obvious for the end-user, but I'd like your thoughts

A few tests were broken too - I tried to clean them up

**Comment by adamint** [comment]
Going ahead and merging

**Comment by molikuner** [comment]
> The Spotify URI classes seemed a little verbose - extending from a base `SpotifyURI` abstract class seems a little cleaner - do you agree?

Yes. But I would prefer sth. like this:
```Kotlin
sealed class SpotifyUri(input: String, type: String) {
    val uri: String
    val id: String

    init {
        val realData = input.replace(" ", "")
        this.uri = realData.add(type)
        this.id = realData.remove(type)
    }
}

class AlbumURI(input: String) : SpotifyUri(input, "album")

class ArtistURI(input: String) : SpotifyUri(input, "artist")
...
```
> I think it would be better to throw a subtype of `BadRequestionException` in the `SpotifyUri` classes instead of `IllegalArgumentException` to make it a little more obvious for the end-user...

I agree it's probably better to have your own exception for that. But I think you should not extend "BadRequestException", because it is likely that the class is only used internally and only for requests, but could also be used elsewhere. So I think you should directly extend "IllegalArgumentException".

**Pull request merged**
